name: Prisma Cloud IaC Scan Example
on: 
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  prisma_cloud_iac_scan:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud IaC Scan to check 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          PRISMA_API_URL: https://api.uk.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
	  
      - name: Upload Prisma IAC scan results
	      uses: github/codeql-action/upload-sarif@v1
	      if: always()
	      with:
           sarif_file: 'results.sarif'
	   
      - name: Archive Scan Results
	      uses: actions/upload-artifact@v2
	      with:
         name: scan-report
	       path: 'results.sarif'
